name: ci-cadastro

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  cypress-tests:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          sparse-checkout: Exemplo03
      - name: Run cadastro de funcionario
        uses: cypress-io/github-action@v5
        with:
          command: npm run cy:test:ex03